import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { fetchUserRepository } from "@/repository/user";
import InitializeUser from "@/components/Initialize/InitializeUser";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const userData = await fetchUserRepository();
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
                <InitializeUser user={userData}>
                    {children}
                    <ToastContainer
                        position="top-center"
                        draggable={false}
                        pauseOnHover={false}
                        autoClose={2500}
                        closeButton={false}
                        hideProgressBar={true}
                        theme="colored"
                    />
                </InitializeUser>
            </body>
        </html>
    );
}
