import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { fetchUserRepository } from "@/repository/user";
import InitializeUser from "@/components/Initialize/InitializeUser";
import ParentSidebar from '@/components/sidebar/ParentSidebar';

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const userData = await fetchUserRepository();
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <InitializeUser user={userData}>
                    <ParentSidebar>
                        <div className="bg-white">
                            <div className="flex justify-between m-2">
                                Dashboard
                                <h1 className="border-l pl-3">Profile</h1>
                            </div>
                        </div>
                        {children}
                        <ToastContainer
                            position="top-center"
                            draggable={false}
                            pauseOnHover={false}
                            autoClose={2500}
                            closeButton={false}
                            hideProgressBar={true}
                            theme="colored"
                        />
                    </ParentSidebar>
                </InitializeUser>
            </body>
        </html>
    );
}
